# Data location
name: "cityscapes"
dataset_root: "data/cityscapes"

# Relative path to train/val/sam_sampling 
train: "leftImg8bit/train"
val: "gtFine/train"

# CSV with SAM regions for train images
sam_sampling: "sam_sampling.csv"

# Train params
max_epochs: 1600